### ISSUE TITLE
Created date not assigned for online (non-batch) surveys

### ISSUE THREAD

**Issue by TimReardon** [MAPC/myschoolcommute#78]
Surveys entered by parents using online interface (either map point location or cross streets) are not assigned a created date, and can therefore not be assigned to a survey set.  

Is this a consequence of the fix that was made for the bulk entry forms?

**Comment by demiurg** [comment]
Yes, because the batch form sets the created field manually, its not automatically populating. However, the modified field should be automatically being populated and can be used instead.

**Comment by TimReardon** [comment]
But that means the online (non-batch) surveys are useless for analysis, unless we manually assign a created date. It seems that your solution to the bulk entry date problem simply created another problem elsewhere.  How do you propose to fix it?

**Comment by demiurg** [comment]
The modified field should be automatically being populated and can be used instead.

**Comment by demiurg** [comment]
I also wouldn't use the word 'simply' in relation to this system. The solution to the bulk entry date problem solved a problem, because it made it required to set the field manually. The field now has to be set manually when creating the survey result in other places. This is an unintended consequence, not a simple consequence and should have been exposed with testing. Fortunately it doesn't impact the data, since a query can be ran to assign the modified value to the created field. I can also set it manually in the user entry form at the creation time.

**Comment by demiurg** [comment]
This is fixed.
